# 开发环境配置

# JPA配置
spring.jpa.hibernate.ddl-auto=${CRS_JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${CRS_JPA_SHOW_SQL:true}

# 开发工具配置
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

# 日志配置
logging.level.org.springframework=${SPRING_FRAMEWORK_LOG_LEVEL:INFO}
logging.level.com.crs=${CRS_LOG_LEVEL:DEBUG}
