# 生产环境配置

# 数据库配置
spring.datasource.url=jdbc:mysql://43.128.145.91:3306/CRS?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai

# JPA配置
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# 开发工具配置
spring.devtools.restart.enabled=false

# 日志配置
logging.level.org.springframework=WARN
logging.level.com.crs=INFO

# 安全配置
server.ssl.enabled=false

#  actuator配置
management.endpoints.web.exposure.include=health,info
